version: '3.8'

services:
  flask-app:
    build:
      context: .  # Sets the build context to the current directory
      dockerfile: Dockerfile  # Specifies the Dockerfile to use
    container_name: Mr_Mito_Backend  # Custom container name for the Flask app
    ports:
      - "5000:5000"  # Maps the container's port 5000 to the host's port 5000
    volumes:
      - .:/app  # Mounts the current directory into the container
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/flask_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine  # Official PostgreSQL image
    container_name: flask_db  # Name for the PostgreSQL container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"  # Maps the container's port 5432 to the host's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Named volume for persisting database data
